# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "498 Orcas St, Morro Bay CA"

# Below the site title
tagline: "Restoring the Best View in Morro Bay"

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: >-
  Orcas St is an amazing modern custom home that fell into disrepair 
  through no fault of its own. We are bringing it back.

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://www.keithbuhler.com"

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl: "/orca"

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /orca/
  - text: About
    url: /orca/about/

# Author information - author info at the bottom of the post
author_name: "Dionysius Buhler"
author_bio: "My name is Dionysius (\"Keith\"). I'm an entrepreneur and educator. I build things and inspire people."
author_url: "https://www.keithbuhler.com"
author_location: "CA"
author_image: authorimage.jpg

# Footer ad banner
banner_image: banner.jpg
banner_url: https://justgoodthemes.com/

# Footer newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"

# Social links in the site footer
twitter_username: "keith_buhler"
facebook_username: "keithedbuhler"
github_username: "keithbuhler"
instagram_username: "keithedbuhler"
linkedin_username: "keithedbuhler"

# http://jekyllrb.com/docs/pagination/
paginate: 6
paginate_path: "/blog/page:num/"
plugins: 
  - jekyll-paginate

permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: false
